name: Desktop Build (Windows & macOS)

on:
  push:
    branches: [ main ] # Сборка будет запускаться при каждом пуше в main
  workflow_dispatch: # Позволяет запустить сборку вручную кнопкой в GitHub

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Запускаем две параллельные виртуальные машины
        os: [ windows-latest, macos-latest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew (macOS only)
        if: matrix.os == 'macos-latest'
        run: chmod +x gradlew

      # Сборка для Windows (запустится только на windows-latest)
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew :composeApp:packageMsi :composeApp:packageExe --stacktrace

      # Сборка для macOS (запустится только на macos-latest)
      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: ./gradlew :composeApp:packageDmg --stacktrace

      # Загрузка Windows файлов
      - name: Upload Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: CineApp-Windows
          path: |
            composeApp/build/compose/binaries/main/msi/*.msi
            composeApp/build/compose/binaries/main/exe/*.exe

      # Загрузка macOS файлов
      - name: Upload macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: CineApp-macOS
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

      # Загрузка готовых файлов в GitHub Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CineApp-${{ matrix.os }}
          path: |
            composeApp/build/compose/binaries/main/exe/*.exe
            composeApp/build/compose/binaries/main/dmg/*.dmg